---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: 安裝完 AFX 硬體後，即可完成 ONTAP 叢集的設定。此過程包含多個相關的配置階段，您需要依序執行這些階段。在此過程中，您可以選擇新增運行 AI Data Engine（AIDE）的資料運算節點（DCN），讓 AFX 儲存叢集和 DCN 叢集能夠作為單一系統運行，並透過同一個 ONTAP 控制平面進行管理。 
---
= 設定 AFX 儲存系統ONTAP集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝完 AFX 硬體後，即可完成 ONTAP 叢集的設定。此過程包含多個相關的配置階段，您需要依序執行這些階段。在此過程中，您可以選擇新增運行 AI Data Engine（AIDE）的資料運算節點（DCN），讓 AFX 儲存叢集和 DCN 叢集能夠作為單一系統運行，並透過同一個 ONTAP 控制平面進行管理。



== 準備設定 AFX 儲存系統

在設定 ONTAP 叢集之前，您應該查看核心 AFX 要求和額外的 AIDE 注意事項，以確保您擁有成功完成設定流程所需的所有資訊和資源。



=== 核心 AFX 要求

設定 AFX 叢集時需要考慮幾個核心需求。

.硬體安裝
請確保您已完成 AFX 系統的硬體安裝。如需詳細資訊，請參閱 link:../install-setup/install-setup-workflow.html["安裝您的 AFX 系統"]。

.基本 IP 位址
您需要以下 IP 位址組態：

* 叢集管理IP位址
+
叢集管理 IP 位址是叢集管理員用來存取管理 SVM 和管理叢集的叢集管理介面的唯一 IPv4 位址。您可以從組織中負責指派 IP 位址的管理員處取得此 IP 位址。

* 網路子網路遮罩
+
在叢集設定期間， ONTAP需要一組適合您的配置的網路介面。如有必要，您可以調整建議。



.其他網路組態
您還需要以下相關的網路資訊：

* 網路閘道 IP 位址
* DNS 網域
* DNS 名稱伺服器 IP 位址
* NTP 伺服器 IP 位址
* 子網路遮罩




=== 其他 AIDE 注意事項

首次安裝和設定 AFX 時，您可以選擇性地包含 NetApp AI Data Engine（AIDE）。如果您打算設定 AIDE，則需要先執行下列操作：

* 務必 https://docs.netapp.com/us-en/ai-data-engine/install-setup/aide-hardware-requirements.html["安裝 AIDE"^]並將運算節點連接到 AFX 儲存網路。
* 取得資料運算節點的位址及任何相關的網路組態。




== 執行初始叢集設定

您可以將筆記型電腦設備連接到 AFX 叢集並設定幾個全域設定值。

.關於此任務
AFX 叢集有四個區域必須進行初始設定。前三個是必需的，最後一個是可選的。

.步驟
. 發現您的集群網路。
+
.. 將您的筆記型電腦連接到管理交換器並存取網路電腦和裝置。
.. 開啟檔案總管。
.. 選擇*網路*；然後右鍵並選擇*刷新*。
.. 選擇任一ONTAP圖示；然後接受螢幕上顯示的任何證書。
+
將顯示系統管理器使用者介面。



. 設定管理員密碼。
+
提供並驗證 `admin`帳戶。選擇*繼續*。

. 設定 AFX 叢集和控制器節點的 IP 位址。
+
提供 IP 位址和子網路遮罩。

. 如果您要將 AI Data Engine 與 AFX 儲存系統一起安裝，請提供三個 AIDE DCN 節點的 IP 位址。
. 設定網路服務，包括 DNS 和 NIS。選擇 *Continue* 。
+
定義您的 DNS 和 NTP 伺服器的詳細資訊。

. 可選擇設定加密。
+
您可以定義集群加密的詳細資訊。選擇*繼續*。

+

NOTE: 有關如何在非 Windows 環境中建立叢集的信息，請參閱 link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html["建立ONTAP叢集並加入節點"^]。



.下一步
您將被重新導向到系統管理員登入頁面。執行中所述的步驟<<完成集群設定>>。



== 完成集群設定

完成初始設定後，您可以使用系統管理員完成ONTAP叢集設定。

.關於此任務
在設定過程中配置了 AFX 系統ONTAP叢集的三個區域。如果可能的話，請完成所有三個，但只需要第一個。

.開始之前
您需要掌握以下資訊：

* VLAN 配置詳細資訊。
* NAS 和/或 S3 配置詳細資訊。


.步驟
. 使用您在初始叢集設定期間提供的管理員帳戶Sign in系統管理員。請注意右上角的彈出窗口，其中有三個配置選項。
. 選擇*VLAN 和標記*並選擇適合您環境的網路選項。
. 選擇*網路服務*並配置預設資料 SVM 的客戶端存取協定。
. 選擇*資料容器*並建立磁碟區或 S3 儲存桶。


.下一步
* 如果您已將 AIDE 納入 AFX 叢集設定中，則需要執行額外的設定步驟，包括授權和驗證。如需更多資訊，請參閱 https://docs.netapp.com/us-en/ai-data-engine/install-setup/cluster-setup-afx.html["設定 AI Data Engine"^]。
* 你應該link:../get-started/prepare-cluster-admin.html["準備管理 AFX"]在生產環境中使用 AFX 叢集之前。




== 相關資訊

* link:../get-started/learn-about-aide.html["了解 NetApp AI Data Engine"]
* link:../administer/configure-svm.html["配置 AFX SVM"]
* link:../get-started/prepare-cluster-admin.html["準備管理 AFX"]

