---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: 安裝 AFX 硬體後，您可以完成叢集設定。此過程涉及兩個相關的配置階段，您需要按順序執行。 
---
= 設定 AFX 儲存系統ONTAP集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝 AFX 硬體後，您可以完成ONTAP叢集設定。此過程涉及兩個相關的配置階段，您需要按順序執行。



== 執行初始叢集設定

您可以將筆記型電腦設備連接到 AFX 叢集並設定幾個全域設定值。

.關於此任務
AFX 叢集有四個區域必須進行初始設定。前三個是必需的，最後一個是可選的。

.開始之前
您需要掌握以下資訊：

* 叢集管理IP位址
+
叢集管理 IP 位址是叢集管理員用來存取管理 SVM 和管理叢集的叢集管理介面的唯一 IPv4 位址。您可以從組織中負責指派 IP 位址的管理員處取得此 IP 位址。

* 網路子網路遮罩
+
在叢集設定期間， ONTAP需要一組適合您的配置的網路介面。如有必要，您可以調整建議。



您還需要以下物品：

* 網路閘道 IP 位址
* DNS 網域
* DNS 名稱伺服器 IP 位址
* NTP 伺服器 IP 位址
* 子網路遮罩


.步驟
. 發現您的集群網路。
+
.. 將您的筆記型電腦連接到管理交換器並存取網路電腦和裝置。
.. 開啟檔案總管。
.. 選擇*網路*；然後右鍵並選擇*刷新*。
.. 選擇任一ONTAP圖示；然後接受螢幕上顯示的任何證書。
+
將顯示系統管理器使用者介面。



. 設定管理員密碼。
+
提供並驗證 `admin`帳戶。選擇*繼續*。

. 配置叢集和控制節點的IP位址。
+
提供 IP 位址和子網路遮罩。

. 設定網路服務。選擇*繼續*。
+
定義您的 DNS 和 NTP 伺服器的詳細資訊。

. 可選擇設定加密。
+
您可以定義集群加密的詳細資訊。選擇*繼續*。



.下一步
您將被重新導向到系統管理員登入頁面。執行中所述的步驟<<完成集群設定>>。



== 完成集群設定

完成初始設定後，您可以使用系統管理員完成ONTAP叢集設定。

.關於此任務
在設定過程中配置了 AFX 系統ONTAP叢集的三個區域。如果可能的話，請完成所有三個，但只需要第一個。

.開始之前
您需要掌握以下資訊：

* VLAN 配置詳細資訊。
* NAS 和/或 S3 配置詳細資訊。


.步驟
. 使用您在初始叢集設定期間提供的管理員帳戶Sign in系統管理員。請注意右上角的彈出窗口，其中有三個配置選項。
. 選擇*VLAN 和標記*並選擇適合您環境的網路選項。
. 選擇*網路服務*並配置預設資料 SVM 的客戶端存取協定。
. 選擇*資料容器*並建立磁碟區或 S3 儲存桶。


.下一步
你應該link:../get-started/prepare-cluster-admin.html["準備管理 AFX"]在生產環境中使用 AFX 叢集之前。

.相關資訊
* link:../administer/configure-svm.html["配置 AFX SVM"]
* link:../get-started/prepare-cluster-admin.html["準備管理 AFX"]

