---
sidebar: sidebar 
permalink: install-afx-2k/install-setup-requirements.html 
keywords: afx, afx 2k, install, setup, requirements, cautions 
summary: 檢查 AFX 2K 儲存控制器和儲存架所需的設備以及搬運注意事項。 
---
= AFX 2K 儲存系統的安裝要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
檢查 AFX 2K 儲存控制器和儲存架所需的設備以及搬運注意事項。



[[equipment-needed-for-install]]
== 安裝所需的設備

要安裝您的 AFX 2K 儲存系統，您需要以下設備和工具。

* 存取 Web 瀏覽器來設定您的儲存系統
* 靜電放電 (ESD) 腕帶
* 手電筒
* 具有 USB/串行連接的筆記型電腦或控制台
* 用於設定存放架 ID 的迴紋針或細頭原子筆
* 2 號十字螺絲刀




[[lifting-precautions]]
== 起重註意事項

AFX 儲存控制器和儲存架很重。抬起和移動這些物品時要小心。



[[storage-controller-weights]]
=== 儲存控制器權重

移動或抬起 AFX 2K 儲存控制器時，請採取必要的預防措施。

AFX 2K 儲存控制器重量可達 64.0 磅（29.03 公斤）。要抬起儲存控制器，請使用兩人或液壓升降機。

.AFX 2K 控制器吊掛注意事項。
image::../media/drw_afx_2k_weight_caution_ieops-2938.svg[AFX 2K 控制器提升注意圖示]



[[storage-shelf-weights]]
=== 倉儲貨架重量

移動或抬起架子時請採取必要的預防措施。

.NX224貨架
NX224 磁碟櫃最大重量可達 60.1 磅（27.3 公斤）。搬運磁碟櫃時，請兩人操作或使用液壓升降機。請將所有組件（包括前後組件）放置在磁碟櫃內，以防止磁碟櫃重量不平衡。

.NX224 磁碟櫃搬運注意事項。
image::../media/drw_nx224_lifting_weight_ieops-2437.svg[NX224 NSM100 提升警告圖標]



[[switch-weights]]
=== 切換權重

移動或抬起開關時，請採取必要的預防措施。

.Cisco Nexus 9808
一台空載的 Cisco 9808 交換器重量可達link:https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9800-series-switches-ds.html#Productspecifications["162 磅（73 公斤），而一台滿載的 Cisco 9808 交換器重量可達 766 磅（347 公斤）。"^]。若要吊起此交換器，請使用液壓升降機。

.卸載 Cisco Nexus 9808 的吊掛注意事項。
image::../media/drw_afx_2k_weight_icon_ieops-2939.svg[Cisco Nexus 9808 提升警示圖示]

.滿載的 Cisco Nexus 9808 吊運注意事項。
image::../media/drw_afx_2k_nexus9808_loaded_weight_caution_ieops-2940.svg[Cisco Nexus 9808 滿載提升警告圖示]

.Cisco Nexus9332D-GX2B
Cisco 9332D-GX2B 的重量可達 link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/aci/nexus9000/9332d-gx2b/cisco-nexus-9332d-gx2b-aci-mode-switch-hardware-installation-guide/m_n93xxx_system_specs.html["12.7 公斤（28.1 磅）"^]。

.Cisco Nexus 9364D-GX2A
一台 Cisco Nexus 9364D-GX2A 交換器的重量可達 link:https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9364d-gx2a/cisco-nexus-9364d-gx2a-nx-os-mode-switch-hardware-installation-guide/m_n93xxx_system_specs.html["58 lb （26.3 kg）"^]。若要抬起此交換器，請使用兩人或液壓升降機。

.Cisco Nexus 9364D-GX2A 吊掛注意事項。
image::../media/drw_afx_2k_9364d_weight_caution_ieops-2942.svg[Cisco Nexus 9364D-GX2A 提升警告圖示]

.相關資訊
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["安全資訊和監管通知"^]


.下一步是什麼？
在您查看完硬體需求後，您link:prepare-hardware.html["準備安裝您的 AFX 2K 儲存系統"]。
