---
sidebar: sidebar 
permalink: get-started/compare-unified-ontap.html 
keywords: afx, afx system, compare afx, compare unified ontap 
summary: NetApp AFX 系統運行客製化的ONTAP特性，它與在AFF和FAS儲存上運行的ONTAP特性（稱為統一ONTAP ）不同。您應該了解 AFX 系統與FAS和AFF系統有何相似之處和不同之處。這提供了寶貴的視角，並且在您的環境中部署 AFX 時會很有幫助。 
---
= 將 AFX 儲存系統與AFF和FAS系統進行比較
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX 系統運行客製化的ONTAP特性，它與在AFF和FAS儲存上運行的ONTAP特性（稱為統一ONTAP ）不同。您應該了解 AFX 系統與FAS和AFF系統有何相似之處和不同之處。這提供了寶貴的視角，並且在您的環境中部署 AFX 時會很有幫助。


TIP: AFX 文件包含統一ONTAP文件網站上各種主題的鏈接，其中詳細介紹了無論ONTAP特性如何都以相同方式運行的功能。附加內容提供了更深入的幫助，可以幫助您管理 AFX 儲存系統。



== 配置差異

AFX 配置與AFF和FAS系統在某些方面有所不同。

高級容量平衡:: 先進的容量平衡功能，使用 `-gdd`CLI 參數，預設對所有FlexGroup磁碟區啟用。




== 不受支援或受限制的 Unified ONTAP功能

NetApp AFX 針對高效能 NAS 和物件工作負載進行了最佳化。因此，它與 AFF 和 FAS 儲存系統存在差異。以下功能在 NetApp AFX 中不可用；此清單按主要功能或功能領域進行分類。您還應根據您的 ONTAP 版本查看 AFX 的更新和變更link:../release-notes/whats-new-9171.html["什麼是新的"]。



=== 區塊儲存和SAN

* SAN 管理和客戶端訪問
* LUN 和 NVMe 命名空間
* 卷的厚配置




=== 骨材和實體存儲

* MetroCluster
* 實體節點擁有的聚合
* RAID 管理
* NetApp聚合加密 (NAE)
* 聚合級重複資料刪除
* SyncMirror （聚合鏡像）
* FabricPool分層
* 負載共享鏡像




=== 資料複製（SnapMirror）


NOTE: Unified ONTAP和 AFX 之間雙向支援所有資料複製，並遵循相同的版本控制限制（詳見下文）。 https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["SnapMirror關係相容的ONTAP版本"^] （除少數例外情況外）。

* 無法從包含 LUN 或 NVMe 命名空間的AFF或FAS系統複製卷
* FlexGroup磁碟區只能從 AFX 複製到 Unified ONTAP版本 9.16.1 或更高版本（因為需要高階容量平衡）。




=== 可管理性

* ONTAPI API（ZAPI）
* 不支援的功能（例如MetroCluster）的 REST API
* REST API 在效能統計方面存在一些初步限制
* AIQ 統一管理器支援
* Grafana Harvest 版本 25.08.1 及更高版本
* NetApp Trident版本 25.10 及更高版本




== 命令列介面的更改

AFX 提供的ONTAP CLI 通常與AFF和FAS系統提供的 CLI 相同。但存在一些差異，包括：

* 與以下相關的新 AFX 指令：
+
** 顯示儲存可用區域的容量
** 啟動媒體


* 沒有與 SAN 相關的命令
* 不再需要聚合管理命令
* 聚合顯示現在顯示整個儲存可用區 (SAZ)




== 相關資訊

* link:../get-started/system-design.html["AFX系統特性"]
* link:../get-started/software-architecture.html["AFX 架構細節"]
* link:../faq-ontap-afx.html["AFX 儲存系統常見問題解答"]
* link:../administer/additional-ontap-cluster.html["額外的 AFX 叢集管理"]
* link:../administer/additional-ontap-svm.html["額外的 AFX SVM 管理"]

