---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: NetApp AFX 儲存系統基於下一代儲存架構，將ONTAP儲存模型發展為分解的高效能 NAS 解決方案。  AFX 採用先進的技術和處理技巧來支援文件和物件工作負載，從而提供極高的效能。 
---
= 了解 AFX 儲存系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX 儲存系統基於下一代儲存架構，將ONTAP儲存模型發展為分解的高效能 NAS 解決方案。  AFX 採用先進的技術和處理技巧來支援文件和物件工作負載，從而提供極高的效能。



== 典型的應用程式工作負載

NetApp AFX 儲存系統滿足了 NAS 和 S3 物件工作負載對高效能和獨立擴充的獨特需求。這些應用程式受益於基於高並發性和平行 I/O 的先進設計。  AFX 非常適合部署和管理多種不同類型應用程式工作負載的組織，包括：

* 與深度學習相關的訓練和迭代模型細化，需要持續的高頻寬和對海量資料集的存取。
* 處理包括文字、圖像和影片在內的多種資料類型。
* 需要嚴格響應時間視窗的低延遲即時推理應用程式。
* 資料科學和機器學習流程可以從資料工程師和資料科學家的自助資料管理中受益。




== 系統設計特點

AFX 系統具有多種設計特點，使其能夠作為高效能 NAS 平台運作。

分離儲存和運算能力:: 與其他NetApp ONTAP儲存系統不同，AFX 叢集的運算和儲存元素是解耦的，並透過交換網路連接。磁碟所有權不再與特定節點綁定，這帶來了許多好處。例如，AFX 叢集的運算和儲存組件可以獨立擴展。
自動化儲存管理:: AFX 儲存管理員已無法存取實體聚合資料。相反，當向叢集新增新的儲存架時，AFX 會自動管理節點的虛擬容量分配以及 RAID 群組配置。這種設計簡化了管理，並為非專業人員提供了管理資料的機會。
叢集的單一儲存池:: 由於NetApp AFX 將儲存節點和機架解耦，因此叢集的所有儲存容量都集中在一個名為儲存可用區 (SAZ) 的池中。 SAZ 中的磁碟和儲存架可供 AFX 叢集中的所有儲存節點進行讀寫操作。此外，發生故障時，所有叢集節點都可以參與磁碟重建。請參閱link:../faq-ontap-afx.html["AFX 儲存系統常見問題解答"]更多詳情請見下文。
高效能:: NetApp AFX 提供高且持續的頻寬以及超低的延遲，因此專為高效能 NAS 和物件工作負載而設計。 AFX 採用最新的現代硬體以及儲存機架，憑藉其獨特的架構，能夠處理高比例的節點和磁碟。將儲存節點擴展到超過典型的 1:1（節點：機架）比例，可以最大限度地發揮磁碟的效能，使其達到極限。該設計為您的關鍵應用提供效率和儲存密度。
獨立且大規模:: 基於解耦的儲存節點和儲存架，AFX 叢集可以根據您的應用需求進行獨立且無中斷的擴充。您可以新增儲存節點來獲得更多 CPU 和吞吐量，或新增儲存架以獲得更多儲存容量和磁碟效能。 NetApp AFX 架構為叢集的最大規模帶來了新的可能性。有關基於您的ONTAP版本的 AFX 叢集的最新限制，請參閱NetAppHardware Universe。
零拷貝資料遷移:: NAS 和物件用戶端存取ONTAP叢集上的磁碟區。您可以無中斷地在節點之間遷移卷，以實現容量和效能平衡目標。使用 Unified ONTAP時，磁碟區遷移是使用SnapMirror技術執行的，這可能需要一些時間並佔用額外的臨時容量。但是，使用 AFX，在共用儲存可用區 (SAZ) 內不再需要資料複製作業。相反，僅移動卷元數據，從而顯著提高效能。請參閱link:../faq-ontap-afx.html["AFX 儲存系統常見問題解答"]更多詳情請見下文。
增強型高可用性功能:: NetApp AFX 為高可用性 (HA) 設定和處理提供了許多增強功能。 AFX 消除了直接連接 HA 夥伴節點的需要，而是允許 HA 對透過內部叢集網路進行通訊。這種設計使管理員可以選擇在資料中心的不同機架或行中部署 HA 對，以增加容錯能力。此外，AFX 零拷貝遷移功能也擴展到了高可用性故障轉移場景。當一個節點發生故障時，其磁碟區將故障轉移到高可用性夥伴節點，以將剩餘的寫入作業提交到磁碟。然後ONTAP將磁碟區均勻地分配到群集中所有倖存的節點上。這意味著在資料放置的初始設計中，您不再需要考慮儲存故障轉移效能。




== 硬體基礎設施

NetApp AFX 儲存系統提供統一的硬體和軟體解決方案，可根據高效能 NAS 客戶的需求建立簡化的體驗。


TIP: 你應該複習一下link:../faq-ontap-afx.html["AFX 儲存系統常見問題解答"]有關硬體互通性和升級選項的詳細資訊。

以下硬體組件與 AFX 叢集一起使用：

* AFX 1K 控制器
* NX224貨架
* Cisco Nexus 9332D-GX2B 或 Nexus 9364D-GX2A 交換機




== 相關資訊

* https://hwu.netapp.com/["NetAppHardware Universe"^]
* https://www.netapp.com/afx/["NetApp AFX"^]

