---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: NetApp AFX 儲存系統基於下一代儲存架構，將ONTAP儲存模型發展為分解的高效能 NAS 解決方案。  AFX 採用先進的技術和處理技巧來支援文件和物件工作負載，從而提供極高的效能。 
---
= 了解 AFX 儲存系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX 儲存系統基於下一代儲存架構，將ONTAP儲存模型發展為分解的高效能 NAS 解決方案。  AFX 採用先進的技術和處理技巧來支援文件和物件工作負載，從而提供極高的效能。



== 典型的應用程式工作負載

NetApp AFX 儲存系統滿足 AI/ML 環境和其他相關以資料為中心的應用程式的典型獨特需求。AFX 儲存系統非常適合管理多種不同工作負載的組織，包括：

* 與深度學習相關的訓練和迭代模型細化，需要持續的高頻寬和對海量資料集的存取。
* 處理包括文字、圖像和影片在內的多種資料類型。
* 需要嚴格響應時間視窗的低延遲即時推理應用程式。
* 資料科學和機器學習流程可以從資料工程師和資料科學家的自助資料管理中受益。
* 需要高並發性和平行 I/O 的工作負載，例如具有 RDMA 傳輸的多 GPU 系統。




== 系統設計特點

AFX 系統具有多種設計特點，使其能夠作為高效能 NAS 平台運作。

分離儲存和運算能力:: 與AFF和FAS儲存系統不同，叢集的 AFX 儲存和運算元素是分開的。  AFX 控制器不限於存取有限的一組本機磁碟。
刪除聚合和 RAID 管理:: 儲存管理員不再需要管理聚合和 RAID 群組。  AFX 處理這些任務，從而簡化管理並為非專業人員提供管理其資料的機會。
叢集的單一儲存池:: 將 AFX 運算和儲存分離，並簡化儲存管理，從而形成單一儲存池。此儲存可用區 (SAZ) 可供 AFX 叢集中的所有控制器節點使用。看link:../faq-ontap-afx.html["AFX 儲存系統常見問題解答"]了解更多詳情。
高效能:: AFX 專為滿足專業 AI/ML 應用程式所需的高效能而建置。它可以更有效地利用現代硬體來提供具有超低延遲的高且持續的頻寬。
操作簡便:: 單一儲存池以及包括自動儲存管理在內的其他功能提供了更簡單的管理和操作模型。
可擴展性:: 叢集中的控制節點和儲存架組可以根據應用需求獨立擴充。添加控制器或機架時，管理要求和中斷有限。
提高資料移動性:: 磁碟區可以在叢集控制器節點之間無中斷地移動，而無需實際複製資料。而是更新元資料目錄和索引指標。這大大提高了典型管理程序以及故障情況下的復原效能。




== 硬體基礎設施

NetApp AFX 儲存系統提供統一的硬體和軟體解決方案，可根據高效能 NAS 客戶的需求建立簡化的體驗。

以下硬體組件與 AFX 叢集一起使用：

* AFX 1K 控制器
* NX224貨架
* Cisco Nexus 9332D-GX2B 或 Nexus 9364D-GX2A 交換機




== 相關資訊

* https://www.netapp.com/afx/["NetApp AFX"^]

